### PR TITLE
Add yaml for Kube Deployment

### PR DESCRIPTION
**Pull request by ajbozarth**
Part of https://github.ibm.com/CODAIT/Usability-Enhancement/issues/2

### CODE REVIEW

**Comment by ajbozarth** [comment]
failed when tested locally. When I access the API url I get a blank page with the text `No API definition provided.` instead of the swagger ui. I consistent;y get this using kube but not docker hub directly.

**Comment by djalova** [comment]
@ajbozarth I get the same error when deploying to cloud

**Comment by MLnick** [comment]
It works locally for me when using the `codait/max-fast-neural-style-transfer` pulled down from Dockerhub.

I rebuilt docker image locally and that works too. So how are you seeing the error exactly?

**Comment by ajbozarth** [comment]
It also works fine for me using Docker Hub directly, so it seems to be an actual kube issue in this case. Once I finish all my tests I plan to back through all the PRs to either merge them (once they're reviewed), open issues on the repos where appropriate, or address any problems (like this one)

**Comment by ajbozarth** [comment]
I'll continue looking into it, but this seems to be the only model with a static swagger ui directory included. Based on some quick research the error we're seeing seems to occur when the UI initialization and config loading occur out of order. The fact this only occurs with the model with that static dir seems connected.

@MLnick you originally wrapped this, why did you include the UI dir in this repo?

**Comment by ajbozarth** [comment]
Opened PR #4 to fix the issue found (It was caused by the port being hard coded in the swagger UI code, which was including statically in this model for some reason). Further testing for this will have to wait until that's merged

**Comment by MLnick** [comment]
@ajbozarth approved and merged #4 - I knew I'd done the custom Swagger UI for that but totally forgot I'd hardcoded it to `localhost:5000`. Doh!

**Pull request merged**
